---

#available datasets
datasets:
  - &dataset_defaults
      train_test_ratio: 0.7
      train_test_seed: 4558636
  - &malnet_txt
      <<: *dataset_defaults

models:
  - &model_defaults 
      - &hyperparameter_defaults 
          architecture: 'De(64):De(32):De(16)'
          lr: 0.0001
          epochs: 100
          k_val: 1
          batch_size: 128
          margin: 0.5
          l2: 0.0001

      - &rs_defaults
          epochs: 100
          use_dropout: True
 
scripts:
  - &download_malnet_androzoo 
      name: parse_androzoo.py 
      parameters:
        split_path: '~/data/malnet/split_info/family/0.01' 
        download_path: '/media/jack/hd/malnet_txt/family/0.01'
        api_key: '9b10aecb742d722bb47660cdc1a2d562e29a5065683c38b69fa90134c9d90db1'  
        overwrite: False
        train:
          download: True
          compress: False
        test:
          download: True
          compress: False
        val:
          download: True
          compress: False

# details of the scripts to be run by main.py
current_script:
  run_scripts:
    - *download_malnet_androzoo
  dataset: *malnet_txt
  device: cuda
  gpus: 1
  processes_per_gpu: 7
  cpu_processes: 10
  
  
    
